/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.lab8;
/**
 *
 * @author Иван
 */
public class MyGame extends javax.swing.JFrame {

    Human pers;
    Clothes cl;
    Work wk;
    Realty rt;
    Medicalcard md;
    buff bf;
    /**
     * Creates new form MyGame
     */
    public MyGame() {
        initComponents();
        pers = new Human();
        cl = new Clothes();
        wk = new Work();
        rt = new Realty();
        md = new Medicalcard();
        bf = new buff();
        this.gamebox.setVisible(false);
        Table.setValueAt("Верх", 0, 0);
        Table.setValueAt("Штаны", 1, 0);
        Table.setValueAt("Обувь", 2, 0);
        Table.setValueAt("Статус одежды", 3, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newhumanbutton = new javax.swing.JButton();
        gamebox = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        buy = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        payment = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        height = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imt = new javax.swing.JLabel();
        healthstatus = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        car = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        imt1 = new javax.swing.JLabel();
        working = new javax.swing.JButton();
        age = new javax.swing.JLabel();
        namework = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        SewUp = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        healthing = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        house = new javax.swing.JLabel();
        buysuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(659, 510));
        setMinimumSize(new java.awt.Dimension(659, 510));

        newhumanbutton.setText("Создать персонажа");
        newhumanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newhumanbuttonActionPerformed(evt);
            }
        });

        jLabel17.setText("Работа");

        name.setText("ИМЯ");

        buy.setText("Купить");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        jLabel19.setText("Жильё");

        jLabel7.setText("Баланс");

        payment.setText("Оплата");

        jLabel11.setText("ИМТ");

        height.setText("Рост");

        jLabel10.setText("Рост");

        jLabel1.setText("Имя");

        imt.setText("ИМТ");

        healthstatus.setText("100");

        jLabel18.setText("Оплата");

        weight.setText("ВЕС");

        car.setText("ТО");

        sex.setText("ПОЛ");

        balance.setText("БАЛАНС");

        imt1.setText("Статуст здоровья");

        working.setText("Работать");
        working.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workingActionPerformed(evt);
            }
        });

        age.setText("ВОЗРАСТ");

        namework.setText("Работа");

        jLabel6.setText("Пол");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Квартира(3000000)", "Машина(500000)" }));

        jLabel20.setText("ТО");

        SewUp.setText("Починка(5$)");
        SewUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SewUpActionPerformed(evt);
            }
        });

        jLabel9.setText("Вес");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Table);

        healthing.setText("Лечиться(10$)");
        healthing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthingActionPerformed(evt);
            }
        });

        jLabel3.setText("Возраст");

        house.setText("Жильё");

        buysuit.setText("Купить костюм(1000$)");
        buysuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buysuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameboxLayout = new javax.swing.GroupLayout(gamebox);
        gamebox.setLayout(gameboxLayout);
        gameboxLayout.setHorizontalGroup(
            gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameboxLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameboxLayout.createSequentialGroup()
                        .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(25, 25, 25)
                        .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addGroup(gameboxLayout.createSequentialGroup()
                                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(weight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sex, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(balance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(age, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gameboxLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(gameboxLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addGap(18, 18, 18)
                                                .addComponent(payment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(working)
                                            .addGroup(gameboxLayout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(18, 18, 18)
                                                .addComponent(namework, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(40, 40, 40)
                                        .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(gameboxLayout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(42, 42, 42)
                                                .addComponent(car, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(gameboxLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(house, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameboxLayout.createSequentialGroup()
                                        .addGap(267, 267, 267)
                                        .addComponent(buy)
                                        .addGap(41, 41, 41)))))
                        .addGap(44, 44, 44))
                    .addGroup(gameboxLayout.createSequentialGroup()
                        .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(healthing)
                            .addGroup(gameboxLayout.createSequentialGroup()
                                .addComponent(imt1)
                                .addGap(18, 18, 18)
                                .addComponent(healthstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(gameboxLayout.createSequentialGroup()
                                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(25, 25, 25)
                                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(height, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(imt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameboxLayout.createSequentialGroup()
                                .addComponent(buysuit)
                                .addGap(39, 39, 39))))))
            .addGroup(gameboxLayout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(SewUp))
        );
        gameboxLayout.setVerticalGroup(
            gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(age)
                    .addComponent(jLabel17)
                    .addComponent(namework)
                    .addComponent(jLabel19)
                    .addComponent(house))
                .addGap(18, 18, 18)
                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sex)
                    .addComponent(jLabel6)
                    .addComponent(jLabel18)
                    .addComponent(payment)
                    .addComponent(jLabel20)
                    .addComponent(car))
                .addGap(18, 18, 18)
                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(balance)
                    .addComponent(working)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(weight)
                    .addComponent(buy))
                .addGap(18, 18, 18)
                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameboxLayout.createSequentialGroup()
                        .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(height))
                        .addGap(18, 18, 18)
                        .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(imt))
                        .addGap(18, 18, 18)
                        .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imt1)
                            .addComponent(healthstatus)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(healthing)
                    .addComponent(buysuit))
                .addGap(18, 18, 18)
                .addComponent(SewUp)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(newhumanbutton)
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(gamebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addComponent(newhumanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newhumanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newhumanbuttonActionPerformed
        if(this.newhumanbutton.getText().equals("Загрузить")) {
            this.gamebox.setVisible(true);
            this.newhumanbutton.setVisible(false);
            pers.SetAge(Integer.parseInt(buff.BufAge));
            pers.SetName(buff.BuffName);
            pers.SetSex(buff.BuffSex);
            md.SetHeight(Integer.parseInt(buff.BufHeight));
            md.SetWeight(Integer.parseInt(buff.BufWeight));
            this.age.setText(String.valueOf(pers.GetAge()));
            this.balance.setText(String.valueOf(pers.GetMoney()));
            this.sex.setText(pers.GetSex());
            this.name.setText(pers.GetName());
            this.height.setText(String.valueOf(md.GetHeight()));
            this.weight.setText(String.valueOf(md.GetWeight()));
            this.namework.setText(wk.GetNamework());
            this.payment.setText(String.valueOf(wk.GetPayment()));
            this.house.setText(rt.GetHousing());
            this.car.setText(rt.GetVehicle());
            this.healthstatus.setText(String.valueOf(md.GetHealthStatus()));
            this.imt.setText(md.GetIMT());
            Table.setValueAt(cl.GetBody(), 0, 1);
            Table.setValueAt(cl.GetPants(), 1, 1);
            Table.setValueAt(cl.GetShoes(), 2, 1);
            Table.setValueAt(cl.GetClothesStatus(), 3, 1);
        }
        else {
            newhuman nh = new newhuman();
            nh.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            nh.setVisible(true);
            this.newhumanbutton.setText("Загрузить");
        }
    }//GEN-LAST:event_newhumanbuttonActionPerformed

    private void healthingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthingActionPerformed
        if(pers.GetMoney() >= 10 && md.GetHealthStatus() < 100) {
            md.UpStatus();
            pers.ChangeMoney(-10);
            this.balance.setText(String.valueOf(pers.GetMoney()));
            this.healthstatus.setText(String.valueOf(md.GetHealthStatus()));
        }
    }//GEN-LAST:event_healthingActionPerformed

    private void SewUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SewUpActionPerformed
        if(pers.GetMoney() >= 5 && cl.GetClothesStatus() < 100) {
            pers.ChangeMoney(-5);
            cl.SewUpClothes();
            Table.setValueAt(cl.GetClothesStatus(), 3, 1);
            this.balance.setText(String.valueOf(pers.GetMoney()));
        }
    }//GEN-LAST:event_SewUpActionPerformed

    private void workingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workingActionPerformed
        if(cl.GetClothesStatus() > 0 && md.GetHealthStatus() > 0) {
            pers.ChangeMoney(wk.GetPayment());
            md.DownStatus();
            cl.TearClothes();
            Table.setValueAt(cl.GetClothesStatus(), 3, 1);
            this.balance.setText(String.valueOf(pers.GetMoney()));
            this.healthstatus.setText(String.valueOf(md.GetHealthStatus()));
        }
    }//GEN-LAST:event_workingActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        if (this.jComboBox1.getSelectedItem().equals("Квартира(3000000)") && pers.GetMoney()>3000000) {
            pers.ChangeMoney(-3000000);
            rt.SetHousing("Квартира");
            this.balance.setText(String.valueOf(pers.GetMoney()));
            this.house.setText(rt.GetHousing());
        }
        if (this.jComboBox1.getSelectedItem().equals("Машина(500000)") && pers.GetMoney()>500000) {
            pers.ChangeMoney(-500000);
            this.balance.setText(String.valueOf(pers.GetMoney()));
            rt.SetVehicle("Машина");
            this.car.setText(rt.GetVehicle());
        }
    }//GEN-LAST:event_buyActionPerformed

    private void buysuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buysuitActionPerformed
        if(pers.GetMoney() >= 1000) {
            cl.BuySuit();
            pers.ChangeMoney(-1000);
            this.balance.setText(String.valueOf(pers.GetMoney()));
            Table.setValueAt(cl.GetBody(), 0, 1);
            Table.setValueAt(cl.GetPants(), 1, 1);
            Table.setValueAt(cl.GetShoes(), 2, 1);
            Table.setValueAt(cl.GetClothesStatus(), 3, 1);
            this.buysuit.setVisible(false);
        }
    }//GEN-LAST:event_buysuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SewUp;
    private javax.swing.JTable Table;
    private javax.swing.JLabel age;
    private javax.swing.JLabel balance;
    private javax.swing.JButton buy;
    private javax.swing.JButton buysuit;
    private javax.swing.JLabel car;
    private javax.swing.JPanel gamebox;
    private javax.swing.JButton healthing;
    private javax.swing.JLabel healthstatus;
    private javax.swing.JLabel height;
    private javax.swing.JLabel house;
    private javax.swing.JLabel imt;
    private javax.swing.JLabel imt1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel namework;
    private javax.swing.JButton newhumanbutton;
    private javax.swing.JLabel payment;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel weight;
    private javax.swing.JButton working;
    // End of variables declaration//GEN-END:variables
}
